spring:
  application:
    name: mini-bank
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        "format_sql": true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:7f4c9d8a1b2e3f4051627384950abcdef1234567890fedcba9876543210abcd}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
api:
  key: ${API_KEY:6IHTP4e5GwaPnuRaEu6mKHCZaZi46cvJ}
logging:
  level:
    "org.springframework": INFO
    "com.example": DEBUG

springdoc:
  swagger-ui:
    persist-authorization: true
