spring:
  application:
    name: mini-bank
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/minibank}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0000}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        "format_sql": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
server:
  port: 8080
jwt:
  secret: secret-key-1234567890
  expiration-ms: 3600000
api:
  key: secret-api-key
logging:
  level:
    "org.springframework": INFO
    "com.example": DEBUG
