apiVersion: v1
kind: Secret
metadata:
  name: mini-bank-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: postgres
  JWT_SECRET: 7f4c9d8a1b2e3f4051627384950abcdef1234567890fedcba9876543210abcd
  API_KEY: 6IHTP4e5GwaPnuRaEu6mKHCZaZi46cvJ
