apiVersion: v1
kind: Secret
metadata:
  name: mini-bank-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: postgres
  JWT_SECRET: change-me-very-secure-secret-key-1234567890
  API_KEY: super-secret-api-key
